# Generated by Django 5.1.7 on 2025-03-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, verbose_name="ჟანრი")),
                ("description", models.TextField(verbose_name="აღწერა")),
            ],
            options={
                "verbose_name": "ჟანრი",
                "verbose_name_plural": "ჟანრები",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "წიგნი", "verbose_name_plural": "წიგნები"},
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default=0, max_length=30, verbose_name="ავტორი"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, null=True, verbose_name="გამოცემულია"),
        ),
        migrations.CreateModel(
            name="Borrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.CharField(max_length=50, verbose_name="სახელი და გვარი"),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="გატანის დრო"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="borrowed_by",
                        to="book.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "გატანა",
                "verbose_name_plural": "გატანები",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(to="book.genre"),
        ),
    ]
